version: '3.9'
services:
  db-production:
    container_name: db-production
    image: mysql:latest
    restart: always
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: dota2learning-db
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - "3306:3306"
    volumes:
      - ./data/db-production:/home/db-production
  db-testing:
    container_name: db-testing
    image: mysql:latest
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - "3307:3306"
    volumes:
      - ./data/db-testing:/home/db-testing
volumes:
  data:
